import { LegalHeading, LegalPage } from "@/components/legal-page"

export function PrivacyPage() {
  return (
    <LegalPage title="Privacy" updated="October 4, 2026">
      <p>
        This policy covers Jack AI at j4ck.ai, operated by Jack Gisel. It is a
        personal studio, not a product company.
      </p>
      <LegalHeading>What I collect</LegalHeading>
      <p>
        When you sign in, I store your email address, a display name derived
        from it, and session data. Sessions include a token, expiry, and may
        include IP address and user agent. Magic link emails go to the address
        you submit. If you make a guy, I store their name, color, face, and
        backstory. Messages you send them, and the replies they write, are
        stored too. Each guy also has a private folder in R2 (notes, skills,
        hooks, and files you upload, including spreadsheets and PDFs stored
        as-is). Replies are generated by Cloudflare Workers AI from the thread,
        the guy's backstory, and that folder.
      </p>
      <LegalHeading>Where it lives</LegalHeading>
      <p>
        Account, session, guy, and message records are stored in Cloudflare D1.
        Each guy's files live in Cloudflare R2. The Worker that handles login
        and replies runs on Cloudflare. Magic link emails are sent with
        Cloudflare Email Service. Reply generation uses Cloudflare Workers AI.
      </p>
      <LegalHeading>Cookies</LegalHeading>
      <p>
        A session cookie is set after you click a magic link. It is used to keep
        you signed in. Theme preference and the privacy consent flag are stored
        in your browser with localStorage. If you link the Mac CLI, I store a
        hashed token in D1. The secret itself lives in a config file on that
        Mac.
      </p>
      <LegalHeading>Sharing</LegalHeading>
      <p>
        I do not sell account data. Cloudflare sees what it needs to run the
        site, send mail, and generate replies. I will share records if required
        by law.
      </p>
      <LegalHeading>Retention</LegalHeading>
      <p>
        Sessions expire. Guys and their messages stay until you delete them, or
        until you ask me to delete the account. Email Jack and I will remove
        your user record and related data.
      </p>
    </LegalPage>
  )
}
